

import Providers from "@/components/Providers";
import "../globals.css";
import { AppHeader } from "./ui/AppHeader";




export const metadata = {
  title: " His-mis App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
         <AppHeader />
        {children}
        </Providers>
        
      </body>
    </html>
  );
}
